# Generated by Django 4.1.2 on 2022-10-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_colpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='colpost',
            name='is_article',
            field=models.BooleanField(default=False),
        ),
    ]
