# Generated by Django 4.1.2 on 2022-10-17 13:57
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_colpost_is_published_colpost_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=300, null=True),
        ),
    ]
