# Generated by Django 4.1.2 on 2022-10-17 13:59
import random
import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for row in Post.objects.all():
        row.slug = uuid.uuid4()
        row.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_slug'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
