# Generated by Django 4.1.2 on 2022-10-17 14:11
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221017_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=300, unique=True),
        ),
    ]
